name: Tag
on:
  workflow_dispatch:
  push:
    branches:
      - main
        #paths:
        #- info.json

permissions:
  contents: write

jobs:
  tag:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
      # Not technically needed in this particular case, just a good reminder and doesn't hurt
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get old tags
        run: git fetch --tags origin
      - name: Tag version
        run: |
          tag="v$(jq -r '.version' info.json)"
          existing=$(git tag -l "$tag")

          if [[ -n "$existing" ]]; then
            echo "Tag '$tag' already exists, leaving intact"
            exit 0
          fi

          git config --global user.email "bfullj@gmail.com"
          git config --global user.name "Brandon Fulljames (bot)"

          git tag "$tag" -m "Version $tag"
          git push origin "refs/tags/$tag"
